language: php

php:
  - 5.4
  - 5.5
  - 5.6


before_install:
  - composer self-update
  - cd Public && php -S 127.0.0.1:80&
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - export PATH=$PATH:`pwd`/bin
  - cd -

before_script:
  - composer install
  - phantomjs --version
  - casperjs --version

script: casperjs test ./Tests/Functionnal/application.js --url="http://127.0.0.1/"

notifications:
  disabled: true
